Avoid race when scopeValidation is enabled
aspnet/DependencyInjection pull request #470
Opened 2016-12-21 00:24 UTC by pakrym

Fixes: https://github.com/aspnet/DependencyInjection/issues/467
@halter73 @mikeharder

2017-01-03 23:11 UTC, mikeharder requested changes

2017-01-03 23:11 UTC, mikeharder commented on src/Microsoft.Extensions.DependencyInjection/ServiceLookup/CallSiteValidator.cs
> +                _scopedServices[serviceType] = scoped;
Is it correct to update the value if the key already exists?  Or would it be more correct to use `TryAdd()`, so the value is *not* updated if the key already exists?  Or does it not matter and either would be equally correct?

2017-01-03 23:58 UTC, pakrym commented on src/Microsoft.Extensions.DependencyInjection/ServiceLookup/CallSiteValidator.cs
> +                _scopedServices[serviceType] = scoped;
We are displaying only one scoped service of multiple possible so I don't think there is a difference which one exactly.

2017-01-04 00:10 UTC, mikeharder approved these changes

2017-01-04 00:13 UTC, merged

2017-02-22 03:03 UTC, davidfowl commented
/cc @Eilon @DamianEdwards should this go into 1.1.x?

2017-02-22 03:19 UTC, DamianEdwards commented
I don't know if there's any runway left for 1.1.1. @Eilon?

2017-02-22 03:41 UTC, halter73 commented
Both a pro and con of merging this is that scopeValidation is opt-in. Presumably not many people are calling `collection.BuildServiceProvider(validateScopes: true)`.

2017-02-22 05:14 UTC, davidfowl commented
The problem is that there's no workaround if you do want to use it. That kinda bug IMO classifies as patchable. 1.1.2 maybe?

2017-02-22 06:22 UTC, DamianEdwards commented
Yeah I think it should be considered. I think it'll have to wait for 1.1.2 though

2017-02-22 17:42 UTC, Eilon commented
Too late for the current patch, for sure. Can someone log a new bug for DI's next milestone so that we can consider? Please include some reasonable justification in terms of customer scenario.