Split ServiceProvider/Engine/Scope and allocation optimization
aspnet/DependencyInjection pull request #565
Opened 2017-08-03 17:24 UTC by pakrym

Allocation optimizations:

1. Do not allocate `ServiceScopeFactory` - Engine is IServiceScopeFactory 
2. Do not allocate `ServiceScope` - Scope is IServiceScope
3. Do not allocate empty arrays for empty `IEnumerable` resolves - use Array.Empty instead.
4. Cache singleton values if the were already resolved 

Adds time to first service benchmark.

2017-08-03 17:28 UTC, davidfowl commented on src/DI/ServiceLookup/CallSiteExpressionBuilder.cs
> +            lock (_rootScope.ResolvedServices)
Don't store a local for the result.

2017-08-03 18:34 UTC, davidfowl commented on src/DI/ServiceLookup/ServiceProviderEngine.cs
> +        public event Action<Type, IServiceCallSite> OnCreate;
This is pretty gross.

2017-08-03 18:35 UTC, pakrym commented on src/DI/ServiceLookup/ServiceProviderEngine.cs
> +        public event Action<Type, IServiceCallSite> OnCreate;
I was thinking about it, why is event gross?

2017-08-03 18:36 UTC, pakrym commented on src/DI/ServiceLookup/ServiceProviderEngine.cs
> +        public event Action<Type, IServiceCallSite> OnCreate;
What if there are multiple subscribers?

2017-08-03 21:00 UTC, pakrym commented
Before/After:

```
               Method |     Mode |       Mean |       Error |     StdDev |          Op/s | Scaled | ScaledSD |  Gen 0 | Allocated |
--------------------- |--------- |-----------:|------------:|-----------:|--------------:|-------:|---------:|-------:|----------:|
                 NoDI | Compiled |   4.657 ns |   4.3052 ns |  0.2433 ns | 214,729,261.0 |   1.00 |     0.00 | 0.0038 |      24 B |
            Transient | Compiled |  46.991 ns |  15.1008 ns |  0.8532 ns |  21,280,713.8 |  10.11 |     0.47 | 0.0038 |      24 B |
               Scoped | Compiled |  90.290 ns |  16.4021 ns |  0.9268 ns |  11,075,404.9 |  19.42 |     0.87 |      - |       0 B |
            Singleton | Compiled |  93.450 ns |   7.8450 ns |  0.4433 ns |  10,700,861.3 |  20.10 |     0.89 |      - |       0 B |
         ServiceScope | Compiled | 344.464 ns | 390.6707 ns | 22.0736 ns |   2,903,061.7 |  74.11 |     5.07 | 0.1675 |    1056 B |
 ServiceScopeProvider | Compiled |  49.032 ns |   6.7497 ns |  0.3814 ns |  20,394,837.6 |  10.55 |     0.47 | 0.0038 |      24 B |
      EmptyEnumerable | Compiled |  62.681 ns |  13.3817 ns |  0.7561 ns |  15,953,706.0 |  13.48 |     0.61 | 0.0038 |      24 B |

                 NoDI |    Mixed |   4.296 ns |   0.2727 ns |  0.0154 ns | 232,782,480.6 |   1.00 |     0.00 | 0.0038 |      24 B |
            Transient |    Mixed |  40.930 ns |   3.5344 ns |  0.1997 ns |  24,432,120.2 |   9.53 |     0.05 | 0.0038 |      24 B |
               Scoped |    Mixed |  90.426 ns | 141.3419 ns |  7.9861 ns |  11,058,821.2 |  21.05 |     1.52 |      - |       0 B |
            Singleton |    Mixed |  91.161 ns |  10.9240 ns |  0.6172 ns |  10,969,586.5 |  21.22 |     0.13 |      - |       0 B |
         ServiceScope |    Mixed | 321.141 ns | 167.2157 ns |  9.4480 ns |   3,113,899.3 |  74.76 |     1.81 | 0.1675 |    1056 B |
 ServiceScopeProvider |    Mixed |  50.082 ns |  34.0057 ns |  1.9214 ns |  19,967,359.0 |  11.66 |     0.37 | 0.0038 |      24 B |
      EmptyEnumerable |    Mixed |  63.210 ns |  33.3677 ns |  1.8853 ns |  15,820,271.1 |  14.71 |     0.36 | 0.0038 |      24 B |

                 NoDI |  Runtime |   4.645 ns |   3.3240 ns |  0.1878 ns | 215,267,385.2 |   1.00 |     0.00 | 0.0038 |      24 B |
            Transient |  Runtime | 611.111 ns |  68.1974 ns |  3.8533 ns |   1,636,364.0 | 131.70 |     4.40 | 0.0313 |     200 B |
               Scoped |  Runtime |  87.147 ns |  37.1798 ns |  2.1007 ns |  11,474,886.3 |  18.78 |     0.72 |      - |       0 B |
            Singleton |  Runtime | 100.479 ns | 117.3524 ns |  6.6306 ns |   9,952,281.7 |  21.65 |     1.37 |      - |       0 B |
         ServiceScope |  Runtime | 350.114 ns | 135.8684 ns |  7.6768 ns |   2,856,210.5 |  75.45 |     2.83 | 0.1675 |    1056 B |
 ServiceScopeProvider |  Runtime |  72.924 ns |  39.4990 ns |  2.2318 ns |  13,712,863.0 |  15.72 |     0.65 | 0.0038 |      24 B |
      EmptyEnumerable |  Runtime | 205.361 ns |  44.2545 ns |  2.5005 ns |   4,869,466.9 |  44.26 |     1.53 | 0.0034 |      24 B |


               Method |     Mode |       Mean |      Error |    StdDev |          Op/s | Scaled | ScaledSD |  Gen 0 | Allocated |
--------------------- |--------- |-----------:|-----------:|----------:|--------------:|-------:|---------:|-------:|----------:|
                 NoDI | Compiled |   4.792 ns |  2.6618 ns | 0.1504 ns | 208,691,225.5 |   1.00 |     0.00 | 0.0038 |      24 B |
            Transient | Compiled |  38.267 ns | 12.4743 ns | 0.7048 ns |  26,132,215.2 |   7.99 |     0.24 | 0.0038 |      24 B |
               Scoped | Compiled |  83.927 ns | 35.3786 ns | 1.9990 ns |  11,915,135.8 |  17.53 |     0.56 |      - |       0 B |
            Singleton | Compiled |  87.013 ns | 44.9571 ns | 2.5402 ns |  11,492,515.3 |  18.17 |     0.63 |      - |       0 B |
         ServiceScope | Compiled | 105.683 ns | 20.5121 ns | 1.1590 ns |   9,462,302.4 |  22.07 |     0.59 | 0.0278 |     176 B |
 ServiceScopeProvider | Compiled |  44.696 ns | 24.0783 ns | 1.3605 ns |  22,373,568.2 |   9.33 |     0.33 |      - |       0 B |
      EmptyEnumerable | Compiled |  65.220 ns |  9.0914 ns | 0.5137 ns |  15,332,664.4 |  13.62 |     0.36 |      - |       0 B |

                 NoDI |  Dynamic |   4.517 ns |  0.2877 ns | 0.0163 ns | 221,362,606.9 |   1.00 |     0.00 | 0.0038 |      24 B |
            Transient |  Dynamic |  37.560 ns |  4.6898 ns | 0.2650 ns |  26,623,736.5 |   8.31 |     0.05 | 0.0038 |      24 B |
               Scoped |  Dynamic |  81.197 ns | 29.8157 ns | 1.6846 ns |  12,315,774.8 |  17.97 |     0.31 |      - |       0 B |
            Singleton |  Dynamic |  34.434 ns | 13.6300 ns | 0.7701 ns |  29,041,275.4 |   7.62 |     0.14 |      - |       0 B |
         ServiceScope |  Dynamic | 103.938 ns | 50.6644 ns | 2.8626 ns |   9,621,119.4 |  23.01 |     0.52 | 0.0278 |     176 B |
 ServiceScopeProvider |  Dynamic |  44.329 ns | 35.9630 ns | 2.0320 ns |  22,558,698.1 |   9.81 |     0.37 |      - |       0 B |
      EmptyEnumerable |  Dynamic |  59.223 ns | 12.0977 ns | 0.6835 ns |  16,885,385.5 |  13.11 |     0.13 |      - |       0 B |

                 NoDI |  Runtime |   4.403 ns |  0.5085 ns | 0.0287 ns | 227,118,883.7 |   1.00 |     0.00 | 0.0038 |      24 B |
            Transient |  Runtime | 593.074 ns | 59.3944 ns | 3.3559 ns |   1,686,131.5 | 134.70 |     0.95 | 0.0313 |     200 B |
               Scoped |  Runtime |  88.532 ns | 27.9604 ns | 1.5798 ns |  11,295,328.2 |  20.11 |     0.31 |      - |       0 B |
            Singleton |  Runtime |  86.936 ns | 52.9239 ns | 2.9903 ns |  11,502,679.4 |  19.75 |     0.56 |      - |       0 B |
         ServiceScope |  Runtime | 127.805 ns | 54.7921 ns | 3.0959 ns |   7,824,396.5 |  29.03 |     0.59 | 0.0278 |     176 B |
 ServiceScopeProvider |  Runtime |  66.509 ns | 12.6315 ns | 0.7137 ns |  15,035,478.9 |  15.11 |     0.15 |      - |       0 B |
      EmptyEnumerable |  Runtime | 205.604 ns | 54.3136 ns | 3.0688 ns |   4,863,722.3 |  46.70 |     0.62 | 0.0034 |      24 B |
```

2017-08-03 22:22 UTC, halter73 requested changes

2017-08-03 22:22 UTC, halter73 commented on src/DI/ServiceLookup/IServiceProviderEngine.cs
> +        object GetService(Type serviceType);
Why not just implement IServiceProvider?

2017-08-03 22:22 UTC, halter73 commented on test/DI.Performance/Program.cs
> +            //}
This isn't getting checked in, right?

2017-08-03 22:22 UTC, halter73 commented on test/DI.Performance/configs/CoreConfig.cs
> +            //    .With(RunStrategy.Throughput));
More code you should delete.

2017-08-03 23:06 UTC, halter73 approved these changes

2017-08-04 16:50 UTC, davidfowl commented on src/DI/ServiceLookup/CallSiteExpressionBuilder.cs
> +        protected override Expression VisitServiceScopeFactory(ServiceScopeFactoryCallSite serviceScopeFactoryCallSite, CallSiteExpressionBuilderContext context)
Consider reusing visit singleton.

2017-08-04 16:53 UTC, davidfowl commented on src/DI/ServiceLookup/CallSiteExpressionBuilder.cs
> +                return Expression.Constant(ArrayEmptyMethodInfo.MakeGenericMethod(callSite.ItemType).Invoke(null, Array.Empty<object>()));
Consider generating a call to `Array.Empty<T>` instead of storing the constant.

2017-08-04 16:54 UTC, davidfowl commented on src/DI/ServiceLookup/ServiceProviderEngine.cs
> +        private readonly CallSiteExpressionBuilder ExpressionBuilder;
nit: ExpressionBuilder should be lowercase with _

2017-08-04 16:56 UTC, davidfowl commented on src/DI/ServiceLookup/ServiceProviderEngine.cs
> +                            Task.Run(() => CompileResolver());
Consider not allocating.

2017-08-04 16:57 UTC, davidfowl commented on src/DI/ServiceLookup/ServiceProviderEngine.cs
> +                        return (RealizedServices[serviceType] = p => _callSiteRuntimeResolver.Resolve(callSite, p))(scope);
Turn this into multiple lines.

2017-08-04 16:57 UTC, davidfowl commented on src/DI/ServiceLookup/ServiceProviderEngine.cs
> +                        return CompileResolver()(scope);
Use .Invoke.

2017-08-04 16:59 UTC, davidfowl approved these changes
Small nits.

2017-08-05 04:36 UTC, davidfowl commented on src/DI/ServiceLookup/CallSiteRuntimeResolver.cs
>              var array = Array.CreateInstance(
This still allocates...

2017-08-07 18:11 UTC, merged